# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Verve
tagline:          Just Verve
url:              http://mattchou.github.io/verve
paginate:         1
baseurl:          /
author:
  name:           Matt Chou
  url:            https://twitter.com/chou
  email:          

