# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Verve
tagline:          'Just Verve'
description:      'Description to be added at a later time.</a>.'
url:              http://mattchou.github.io/verve/
baseurl:          http://mattchou.github.io/verve/

author:
  name:           'Matt Chou'
  url:            https://twitter.com/chou

paginate:         5